[build]
  base = "web/"
  command = "npm run build"
  publish = "web/public"
  
[[redirects]]
  from = "/studio"
  to = "https://sonderfloral.sanity.studio/desk"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"